apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: todo-app-namespace
  labels:
    app: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: salhianis20/todo-app
          ports:
            - containerPort: 3000
